export const BlueButton = "min-w-25.75 px-2 h-11.5 bg-[#164190] text-white text-[20px] uppercase transition-all duration-300 ease-in-out hover:scale-105 hover:bg-[#1a4da8] hover:shadow-indigo-500/25 hover:shadow-xl"
export const WhiteButton = "min-w-25.75 px-2 h-11.5 bg-white text-[#164190] text-[20px] uppercase transition-all duration-300 ease-in-out hover:scale-105 hover:bg-white/70 hover:shadow-indigo-500/25 hover:shadow-xl"
export const parrafo_normal = "text-[16px] leading-6 sm:text-[29px] sm:leading-8.5"
export const encabezado_h2 = "text-white text-[30px] sm:text-[70px] ml-auto uppercase font-medium py-2 px-4 w-fit"
export const encabezado_h3 = "text-white text-[20px] sm:text-[50px] uppercase font-medium py-2 px-4 w-fit"
export const encabezado_h4 = "text-white text-[24px] uppercase font-medium py-2 px-4 w-fit"
export const stroke_text = "text-transparent font-medium [-webkit-text-stroke-width:1px] [-webkit-text-stroke-color:white]"